---
# https://raw.githubusercontent.com/kubernetes/kubernetes/v1.5.2/cluster/addons/fluentd-elasticsearch/es-controller.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging-v1
  namespace: "kube-system"
  labels:
    k8s-app: elasticsearch-logging
    version: "v2.4.1"
    kubernetes.io/cluster-service: "true"
spec:
  serviceName: elasticsearch-logging
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: "v2.4.1"
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: "v2.4.1"
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: "192.168.10.96:5000/gcr.io/google_containers/elasticsearch:v2.4.1"
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: es-persistent-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10000Mi
      storageClassName: local-storage
