apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app: thanos-query
  name: thanos-query
spec:
  selector:
    app: thanos-query
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    nodePort: 30901
    name: http-query
