apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: gpu-container
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      #image: private-registry.k8s.tuputech.com/tupu/tensoflow:tensoflow1.3.0-python2.7.5-cuda8.0-cudnn7
      image: tensorflow/serving:1.9.0-devel-gpu
      resources:
        limits:
          nvidia.com/gpu: 1
      command: ["tail"]
      args: ["-f", "/dev/null"]
