---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-persistent-storage1
  labels:
     localstorage: es-pv
  annotations:
    volume.alpha.kubernetes.io/node-affinity: >
      {
         "requiredDuringSchedulingIgnoredDuringExecution": {
           "nodeSelectorTerms": [
            { "matchExpressions": [
               { "key": "kubernetes.io/hostname",
                 "operator": "In",
                 "values": ["k8s-3"]
               }
           ]}
         ]}
      }
spec:
  capacity:
    storage: 10000Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  flexVolume:
    driver: "flex/fileblkdev"
    fsType: "xfs"
    options:
      blkfile: "/pv-data/es-persistent-storage1.img"
      size: "10000M"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-persistent-storage2
  labels:
     localstorage: es-pv
  annotations:
    volume.alpha.kubernetes.io/node-affinity: >
      {
         "requiredDuringSchedulingIgnoredDuringExecution": {
           "nodeSelectorTerms": [
            { "matchExpressions": [
               { "key": "kubernetes.io/hostname",
                 "operator": "In",
                 "values": ["k8s-2"]
               }
           ]}
         ]}
      }
spec:
  capacity:
    storage: 10000Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  flexVolume:
    driver: "flex/fileblkdev"
    fsType: "xfs"
    options:
      blkfile: "/pv-data/es-persistent-storage2.img"
      size: "10000M"
