apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-__YOUR_GITLAB_BUILD_NAMESPACE__
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
  name: admin-__YOUR_GITLAB_BUILD_NAMESPACE__
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-__YOUR_GITLAB_BUILD_NAMESPACE__
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
subjects:
  - kind: ServiceAccount
    name: admin-__YOUR_GITLAB_BUILD_NAMESPACE__
    namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
roleRef:
  kind: Role
  name: admin-__YOUR_GITLAB_BUILD_NAMESPACE__
  apiGroup: rbac.authorization.k8s.io
