apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    dcos-app: php-apache
spec:
  ports:
    - port: 80
      targetPort: 80
      # TCP/UDP default TCP
      protocol: TCP
  selector:
    dcos-app: php-apache
